global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'quarkus-app-monitoring'
    scrape_interval: 5s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['quarkus-app-monitoring:8080'] #Servidor da minha aplicação